version: "3.7"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: webmarkdown-nginx
    container_name: webmarkdown-nginx
    ports:
      - 8000:8000
    networks:
      - django-net
    volumes:
      - ./webmarkdown/static:/static
    depends_on: 
      - django

  django:
    build:
      context: ./webmarkdown
      dockerfile: Dockerfile
    image: webmarkdown-django
    container_name: webmarkdown-django
    expose:
      - "8001"
    networks:
      - django-net
    volumes:
      - ./webmarkdown:/home/webmarkdown/
    depends_on:
      - db
    ports:
      - 8888:8888
    environment:
      - DATABASE_ENGINE=django.db.backends.postgresql_psycopg2
      - DATABASE_DB=django_db
      - DATABASE_USER=django_db_user
      - DATABASE_PASSWORD=password1234
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

  db:
    image: postgres:11.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django-net
    environment:
      - POSTGRES_USER=django_db_user
      - POSTGRES_PASSWORD=password1234
      - POSTGRES_DB=django_db

networks:
  django-net:
    driver: bridge

volumes:
  postgres_data: