version: "3.7"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: webmarkdown-nginx
    container_name: webmarkdown-nginx
    ports:
      - 8000:8000
    networks:
      - django-net
    volumes:
      - ./webmarkdown/static:/static
    depends_on: 
      - django

  django:
    build:
      context: ./webmarkdown
      dockerfile: Dockerfile
    image: webmarkdown-django
    container_name: webmarkdown-django
    expose:
      - "8001"
    networks:
      - django-net
    volumes:
      - ./webmarkdown:/home/webmarkdown/
    depends_on:
      - postgres
    ports:
      - 8888:8888

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django-net

networks:
  django-net:
    driver: bridge

volumes:
    postgres_data: