version: "3.7"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: lend-nginx
    container_name: lend-nginx
    ports:
      - 8000:8000
    networks:
      - django-net
    volumes:
      - ./lendings/static:/static
    depends_on: 
      - django

  django:
    build:
      context: ./webmarkdown
      dockerfile: Dockerfile
    image: webmarkdown-django
    container_name: webmarkdown-django
    expose:
      - "8001"
    networks:
      - django-net
    volumes:
      - ./webmarkdown:/home/webmarkdown/
    depends_on:
      - postgres
    ports:
      - 8888:8888

  postgres:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    image: webmarkdown-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=django_db_user
      - POSTGRES_PASSWORD=password1234
      - POSTGRES_DB=django_db
    networks:
      - django-net

networks:
  django-net:
    driver: bridge

volumes:
    postgres_data: